### PR TITLE
Admin Gamestate: handle sendReportsTo not loaded (undefined)

### PR DESCRIPTION
**Pull request by cabeese**

### CODE REVIEW

**Comment by RvanB** [comment]
It still is requiring a reload for the emails to show up, any idea how to fix?

image

**Comment by cabeese** [comment]
@RvanB I'm not seeing the issue you're seeing. it seems to load the list of recipients just fine initially for me. tested locally and with the test site, and in both Chrome and Firefox. Can you give me more details on how/where you're seeing that behavior?

**Comment by RvanB** [comment]
This is how I can reproduce the problem:

1. Navigate to game control panel, emails will show correctly the first time.
2. Navigate to any other page, I've been clicking the GPH logo to go back to homepage.
3. Navigate back to game control panel, emails no longer visible.
4. Reload the page, emails are visible again.

**Comment by cabeese** [comment]
@RvanB Awesome, thank you. Was able to reproduce with your steps and I think I have it actually fixed now. FWIW, I realized that I was trying to add `sendReportsTo` to the component state when there's no reason for that; it should just be referenced as a prop. A few other existing things had that too which threw me off.

**Review by RvanB — APPROVED** [review]
Looks great! Glad it was an easy fix.

**Pull request merged**
